apiVersion: v1
kind: Template
metadata:
  name: mariadb-backup-template
  annotations:
    description: 'Template for MariaDB container backup job'
    tags: 'database'
parameters:
  - name: MARIADB_BACKUP_KEEP
    description: 'Number of backups to keep'
    value: '5'
  - name: MARIADB_BACKUP_SCHEDULE
    description: 'Cron-like schedule expression. Default: Every hour at :55'
    value: '55 * * * *'
  - name: MARIADB_USER
    description: 'MariaDB user (if empty root will be used)'
    value: 'root'
  - name: MARIADB_PASSWORD
    description: 'Required: MariaDB user password (if MARIADB_USER not used please fill root-pwd).'
  - name: MARIADB_SERVICE_HOST
    description: 'Required: MariaDB Service Name.'
  - name: MARIADB_BACKUP_DATABASE
    description: 'Required: MariaDB Database to backup.'
  - name: MARIADB_BACKUP_VOLUME_CLAIM
    description: 'Required: Name of the volume claim to be used as storage.'
  - name: MARIADB_SERVICE_PORT
    description: 'MariaDB Service PORT'
    value: '3306'
  - name: ICINGA_USERNAME
    description: 'Required: MariaDB Database to backup.'
  - name: ICINGA_PASSWORD
    description: 'Required: MariaDB Database to backup.'
objects:
  - apiVersion: batch/v2alpha1
    kind: ScheduledJob
    metadata:
      name: mariadb-backup
    spec:
      schedule: ${MARIADB_BACKUP_SCHEDULE}
      concurrencyPolicy: Forbid
      jobTemplate:
        spec:
          template:
            spec:
              volumes:
                - name: mariadb-backup
                  persistentVolumeClaim:
                    claimName: ${MARIADB_BACKUP_VOLUME_CLAIM}
              containers:
                - name: mariadb-backup
                  image: 'registry.access.redhat.com/rhscl/mariadb-101-rhel7:10.1'
                  command:
                    - 'bash'
                    - '-eo'
                    - 'pipefail'
                    - '-c'
                    - > 
                      trap "echo Backup failed; exit 0" ERR; 
                      FILENAME=backup-${MARIADB_BACKUP_DATABASE}-`date +%Y-%m-%d_%H%M%S`.sql.gz;
                      time (find /mariadb-backup -type f -name "backup-${MARIADB_BACKUP_DATABASE}-*"  -exec ls -1tr "{}" + | head -n -${MARIADB_BACKUP_KEEP} | xargs rm -fr; 
                      mysqldump -u$MARIADB_USER -p$MARIADB_PASSWORD -h$MARIADB_SERVICE_HOST -P$MARIADB_SERVICE_PORT --skip-lock-tables --quick --add-drop-database --routines ${MARIADB_BACKUP_DATABASE} | gzip > /mariadb-backup/$FILENAME); 
                      echo "Icinga Response:";
                      curl -k -s -u $ICINGA_USERNAME:"$ICINGA_PASSWORD" -H 'Accept: application/json' -X POST 'https://monitori:5665/v1/actions/process-check-result?service=openshift-prod!check_passive-pitc-openproject-prod-db-backup_monitor.rz.puzzle.ch' -d '{ "exit_status": 0, "plugin_output": "backup ok" }';
                      echo "";
                      echo "Backup successful"; du -h /mariadb-backup/$FILENAME; 
                      echo "to restore the backup to the serviced host use: $ mysql -u$MARIADB_USER -p$MARIADB_PASSWORD -h$MARIADB_SERVICE_HOST < /mariadb-backup/backupfile (unzipped)"
                  env:
                    - name: MARIADB_BACKUP_KEEP
                      value: ${MARIADB_BACKUP_KEEP}
                    - name: MARIADB_USER
                      value: ${MARIADB_USER}
                    - name: MARIADB_PASSWORD
                      value: ${MARIADB_PASSWORD}
                    - name: MARIADB_SERVICE_HOST
                      value: ${MARIADB_SERVICE_HOST}
                    - name: MARIADB_SERVICE_PORT
                      value: ${MARIADB_SERVICE_PORT}
                    - name: MARIADB_BACKUP_DATABASE
                      value: ${MARIADB_BACKUP_DATABASE}
                    - name: ICINGA_USERNAME
                      value: ${ICINGA_USERNAME}
                    - name: ICINGA_PASSWORD
                      value: ${ICINGA_PASSWORD}
                  volumeMounts:
                    - name: mariadb-backup
                      mountPath: /mariadb-backup
              restartPolicy: Never

